### ISSUE TITLE
kibana-logging service cannot access

### ISSUE THREAD

**Issue by zhangguanzhang** [kairen/kube-ansible#113]
```bash
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services \"kibana-logging\" is forbidden: User \"system:anonymous\" cannot get services/proxy in the namespace \"kube-system\"",
  "reason": "Forbidden",
  "details": {
    "name": "kibana-logging",
    "kind": "services"
  },
  "code": 403
}
```

**Comment by zhangguanzhang** [comment]
I just know the RBAC's effect, i could not write it to access, can you write for me?

**Comment by kairen** [comment]
You can refer the following file to create RBAC for `kube-logging`:
https://github.com/kairen/kube-ansible/blob/996613e18c2397151882f2ab753131d1fe4cb4c7/roles/k8s-addon/templates/dashboard/dashboard-anonymous-rbac.yml.j2#L1-L28
