### ISSUE TITLE
TLS issue

### ISSUE THREAD

**Issue by kleuf** [kairen/kube-ansible#122]
Hi

Firstly, thank you for the awesome work with this repo.

I am stuck in my process of creating a cluster.

The script runs fine until it gets to the: "TASK [k8s-setup : Create kube-apiserver to kubelet RBAC]" part.

Error im getting: 
"fatal: [172.24.49.100 -> 172.24.49.100]: FAILED! => {"attempts": 10, "changed": true, "cmd": ["/usr/local/bin/kubectl", "--kubeconfig=/etc/kubernetes/admin.conf", "apply", "-f", "/tmp/apiserver-to-kubelet-rbac.yml"], "delta": "0:00:00.074493", "end": "2018-09-06 14:30:49.764857", "msg": "non-zero return code", "rc": 1, "start": "2018-09-06 14:30:49.690364", "stderr": "unable to recognize \"/tmp/apiserver-to-kubelet-rbac.yml\": Get https://:8443/api?timeout=32s: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config\nunable to recognize \"/tmp/apiserver-to-kubelet-rbac.yml\": Get https://:8443/api?timeout=32s: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config", "stderr_lines": ["unable to recognize \"/tmp/apiserver-to-kubelet-rbac.yml\": Get https://:8443/api?timeout=32s: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config", "unable to recognize \"/tmp/apiserver-to-kubelet-rbac.yml\": Get https://:8443/api?timeout=32s: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config"], "stdout": "", "stdout_lines": []}"

Im also getting this error whenever i try to use kubectl 

Unable to connect to the server: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config

So it would seem that the issue is that nothing can invoke the command kubectl

Please, any help will be greatly appreciated

**Comment by kleuf** [comment]
found the issue, it was because i did not specify a ip in the all.yaml under the vip entry

**Comment by MrRightSol** [comment]
So what IP you end up using, the first master or a random one?
