### ISSUE TITLE
Dashboard access

### ISSUE THREAD

**Issue by tickers** [kairen/kube-ansible#128]
setup completed zero errors on cent OS 7 vm's running in vmware.
kubectl retrieves everything, get pods services describe etc.
kubectl proxy then running

http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
get's me this
Error: 'dial tcp 10.244.1.6:8443: connect: network is unreachable'
Trying to reach: 'https://10.244.1.6:8443/'

kubectl -n kube-system get po,svc
NAME                                       READY     STATUS    RESTARTS   AGE
pod/calico-node-7gvv8                      2/2       Running   4          6h
pod/calico-node-gqxz2                      2/2       Running   4          6h
pod/coredns-6d98b868c7-slk7m               1/1       Running   1          4h
pod/elasticsearch-logging-0                1/1       Running   1          3h
pod/fluentd-es-8tw67                       1/1       Running   1          3h
pod/fluentd-es-q6fj6                       1/1       Running   1          3h
pod/kibana-logging-56c4d58dcd-blcxh        1/1       Running   1          3h
pod/kube-proxy-7vqh5                       1/1       Running   3          6h
pod/kube-proxy-vb2fs                       1/1       Running   3          6h
pod/kubernetes-dashboard-6948bdb78-wb59s   1/1       Running   1          4h
pod/metrics-server-86bd9d7667-lwpg6        1/1       Running   1          4h

NAME                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
service/calico-typha              ClusterIP   10.111.173.6     <none>        5473/TCP                 6h
service/elasticsearch-logging     ClusterIP   10.111.176.201   <none>        9200/TCP                 3h
service/kibana-logging            ClusterIP   10.111.132.176   <none>        5601/TCP                 3h
service/kube-controller-manager   ClusterIP   None             <none>        10252/TCP                1h
service/kube-dns                  ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   6h
service/kube-scheduler            ClusterIP   None             <none>        10251/TCP                1h
service/kubelet                   ClusterIP   None             <none>        10250/TCP                3h
service/kubernetes-dashboard      ClusterIP   10.106.191.94    <none>        443/TCP                  6h
service/metrics-server            ClusterIP   10.103.82.224    <none>        443/TCP                  6h

What else can I check?

**Comment by kairen** [comment]
Could you check pod network is reachable from Kubernetes nodes?
