### ISSUE TITLE
API server certificate

### ISSUE THREAD

**Issue by thbeh** [kairen/kube-ansible#129]
Hi, I am running a couple of applications that checked for API server certificate and your ansible doesn't seem to contain the right hostnames (the default / usual API hostname is kubernetes.default.svc, but your certificate seems to have only kubernetes.default). Where could I changed that?  Thanks

**Comment by kairen** [comment]
Hi @thbeh, You can modify this line to add your need.

https://github.com/kairen/kube-ansible/blob/eae089cf3f47a7dd8ccf4f00ec7bda58191edbf1/roles/cert/defaults/main.yml#L5
