### ISSUE TITLE
centos07, dict object' has no attribute u'ansible_eth1'"

### ISSUE THREAD

**Issue by Tinuz** [kairen/kube-ansible#76]
Trying to run a vagrant build based upon centos7, after a few minutes this error keeps appearing.

TASK [etcd : Copy Etcd conf template file] *************************************
fatal: [172.16.35.10]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: https://{{ etcd_ip_addr }}:{{ etcd_peer_port }}: {% if etcd_iface != '' %}{{ hostvars[inventory_hostname]['ansible_' + etcd_iface].ipv4.address }} {%- else %}{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}{% endif %}: 'dict object' has no attribute u'ansible_eth1'"}

Tried to run the vagrant build using ubuntu as os, this runs without errors.

**Comment by kairen** [comment]
@Tinuz Thank you for your report, the problem is this iface does not exist on 
 the machine, please checking centos7 iface name, I think it is `enp0s8`.
