### ISSUE TITLE
 ETCD enable and started failed

### ISSUE THREAD

**Issue by HamzaK8s** [kairen/kube-ansible#96]
Hello,
I'm trying to use your code to setup a HA k8s but unfortunately I get this error :
fatal: [Master-k8s-2]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service etcd: Job for etcd.service failed because a timeout was exceeded. See \"systemctl status etcd.service\" and \"journalctl -xe\" for details.\n"}

and when I check the logs I see error: tls: bad certificate)

do you have any idea why ?

Thank you for your reply

**Comment by bravosierrasierra** [comment]
use ip addresses instead DNS-names in inventory file

**Comment by kairen** [comment]
I think we need to support domain name, I will modify in this month.
